# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "t-mtsmt/REMnux"
  
  config.vm.hostname = "remnux-analysis"

  config.vm.provider "virtualbox" do |vb|
    # Set a short, simple name for the VM

    vb.gui = true

    vb.memory = "4096"
    vb.cpus = 2

    # Set video memory
    vb.customize ["modifyvm", :id, "--vram", "128"]
    
    # Disable audio to reduce attack surface
    vb.customize ["modifyvm", :id, "--audio", "none"]

  end

  # Shell provisioner to install packages
  config.vm.provision "shell", path: "install.sh"

end

